### PR TITLE
Cybex

### PR DESCRIPTION
**Pull request by jawad421**
Jawad Akram, Abdullah Saleem, Abdul Qayyum

### CODE REVIEW

**Comment by SangramChavan** [comment]
The table is pending.

Repository link missing. Please check this https://ieeemadc.github.io/IEEEmadC-wiki/AllrounderPropertyManagementSystem submission and update the file accordingly.

**Comment by jawad421** [comment]
I have made the changes(Table). Now where to submit it?

**Comment by SangramChavan** [comment]
Submit again or you can paste the update here

**Comment by jawad421** [comment]
Ok

**Comment by jawad421** [comment]
How to submit again. Please send ma some details.

**Comment by jawad421** [comment]
## Table

<table style="width:100%">
  <tr>
    <th>Executable</th>
    <th>Repository</th> 
    <th>Team</th>
    <th>Description</th>
     <th>Location</th>
     <th>License</th>
     <th>Team Member</th>
           
  </tr>
  <tr>
    <td><a href="https://drive.google.com/open?id=1It_jAFK24PjNN69rYVICVP1fphrLLb5k">apks</a></td>
         <td><a href="https://github.com/jawad421/knockdoor">Knock Door Android App</a></td>
    <td>Cybex</td>
     <td>Home Services Android App</td>
         <td>Pakistan</td> 
          <td>MIT</td> 
         <td>Jawad Akram,Abdullah Saleem, Abdul Qayyum</td> 
           </tr>

</table>

**Comment by SangramChavan** [comment]
Where is the code ?

**Comment by jawad421** [comment]
Our App code is greater than 25 Mb and they are not possible to send Github
but i send the essential code of app to Github.

**Comment by SangramChavan** [comment]
GitHub Supports a larger volume of files.  All the participants have already uploaded the code.  Size is not an issue here. Without code, we can not consider the app for judging.

**Comment by jawad421** [comment]
When i send the file to Github they show the erroe message file size is
larg please submit the file less than 25Mb

**Comment by jawad421** [comment]
I am send the code again or send the code through drive.

**Comment by SangramChavan** [comment]
Okey

**Comment by jawad421** [comment]
I am send the code through Google drive and i send the link to you through
Gmail.

**Comment by jawad421** [comment]
Team: cybex
Source code app

https://drive.google.com/open?id=1f9jhl8bM8oBYQUF0EKrROgX6cM00Cdn7

**Pull request merged**
