### PR TITLE
Wedding Planner

### PR DESCRIPTION
**Pull request by AmrTelbani**
Amr Telbani , Khaliel Assar

### CODE REVIEW

**Comment by SangramChavan** [comment]
Can you please share the Github link and a shot summer like 

| OS | App File | Team Name | Short Description | Licence | Country | Author |

Example :
|Android|[Bizspot.apk](https://github.com/JihedChalghaf/Biz-Spot/blob/master/Apk/BizspotApp.apk) | [4INSAT](https://github.com/JihedChalghaf/Biz-Spot) | [A Network of business owners and service providers](https://www.youtube.com/watch?v=YKQZ-_8ZWIw) | MIT | Tunisia | [Jihed Chalghaf](https://github.com/jihedchalghaf) |

**Comment by AmrTelbani** [comment]
| Android |<a href="https://ufile.io/rucgh9g6"> WeddingPlanner.apk </a> | Masters | <a href="https://youtu.be/2VyHPp-W52o" rel="nofollow"> Wedding Planner Application is an android application for people who are looking for buy or rent stuff for marriage and for sellers of this stuff</a> | MIT | Palestine| <a href="https://github.com/AmrTelbani">Amr Telbani</a> |</p>

**Comment by AmrTelbani** [comment]
you want it like this? 
if need anything more please notify me
thank you

**Comment by SangramChavan** [comment]
Submission looks good. This year there is good participation form Palestine.
I would really appreciate, if you add the apk in your current repo.

**Comment by AmrTelbani** [comment]
| Android |<a href="https://github.com/AmrTelbani/WeddingPlanner/raw/b3c474913d4eb5e567a7bbc70e4b2764780acc0e/Wedding%20Planner.apk"> WeddingPlanner.apk </a> | Masters | <a href="https://youtu.be/2VyHPp-W52o" rel="nofollow"> Wedding Planner Application is an android application for people who are looking for buy or rent stuff for marriage and for sellers of this stuff</a> | MIT | Palestine| <a href="https://github.com/AmrTelbani">Amr Telbani</a> |</p>

**Comment by AmrTelbani** [comment]
oh thank you very much for these words and for making this competition, 
I hope my hard work will pay in the end.
I edited to make a new comment with the changes you asked, please see it and tell me if something is missing.
thank you very much.

**Pull request merged**
