### PR TITLE
Stadium Guard

### PR DESCRIPTION
**Pull request by neenutomy1**
Complete platform for security in stadium

### CODE REVIEW

**Review by neenutomy1 — COMMENTED** [review]
Change

**Comment by neenutomy1** [comment]
I have verified my app but it is not reflecting in madc page.
Team name:mind Benders

**Comment by SangramChavan** [comment]
Because you submitted it in the wrong place.
Following is your file link 
https://github.com/IEEEmadC/IEEEmadC-wiki/blob/gh-pages/wiki/Stadium%20Guard.md

Please update is asap many things are missing.

**Comment by neenutomy1** [comment]
What I have to do????

**Comment by SangramChavan** [comment]
Kindly submit the code.

**Pull request merged**
